version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: nestjs-mysql
    environment:
      MYSQL_ROOT_PASSWORD: sagar  
      MYSQL_DATABASE: booksdb
      MYSQL_USER: sagar
      MYSQL_PASSWORD: sagar123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
